# Generated by Django 5.2.10 on 2026-01-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
