# Generated by Django 5.2.10 on 2026-01-14 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_remove_mensalidade_paga_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atipico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2026, 1, 14, 22, 23, 2, 236573, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.CharField(default='Responsável não informado', max_length=200),
            preserve_default=False,
        ),
    ]
