# Generated by Django 5.2.10 on 2026-01-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_atipico_aluno_data_pagamento_aluno_observacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='observacoes',
            new_name='observacoes_pedagogicas',
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_atipico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
