# Generated by Django 5.2.10 on 2026-01-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_rename_observacoes_aluno_observacoes_pedagogicas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': [('pode_ver_dados_pedagogicos', 'Pode ver dados pedagógicos do aluno')]},
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='observacoes_pedagogicas',
            new_name='observacoes',
        ),
    ]
