# Generated by Django 5.2.10 on 2026-01-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_alter_aluno_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_pagamento',
        ),
    ]
