# Generated by Django 5.2.10 on 2026-01-15 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_remove_aluno_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
