# Generated by Django 5.2.8 on 2026-01-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_mensalidade_criado_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
