# Generated by Django 5.2.8 on 2026-01-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_fechamentomensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='forma',
            field=models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], max_length=10),
        ),
    ]
