# Generated by Django 5.2.8 on 2026-01-17 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_alter_pagamento_forma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensalidade',
            options={'ordering': ['vencimento']},
        ),
        migrations.AddField(
            model_name='aluno',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do responsável'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='atipico',
            field=models.BooleanField(default=False, verbose_name='Aluno atípico'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.CharField(max_length=200, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tipo_atipico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de atipicidade'),
        ),
    ]
