# Generated by Django 5.2.10 on 2026-01-17 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0012_alter_mensalidade_options_aluno_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=8, verbose_name='Valor da mensalidade'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='mensalidade',
            unique_together={('aluno', 'vencimento')},
        ),
    ]
