# Generated by Django 5.2.10 on 2026-01-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_aluno_valor_mensalidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FechamentoMensal',
        ),
        migrations.AlterUniqueTogether(
            name='mensalidade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='atipico',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='tipo_atipico',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='valor_mensalidade',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
