# Generated by Django 5.2.10 on 2026-01-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_delete_fechamentomensal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensalidade',
            options={},
        ),
        migrations.RenameField(
            model_name='mensalidade',
            old_name='criado_em',
            new_name='criada_em',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone_responsavel',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='aluno',
            name='atipico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_atipico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da mensalidade'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma',
            field=models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão')], max_length=20),
        ),
    ]
