# Generated by Django 5.2.8 on 2026-01-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0015_alter_mensalidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='tipo_atipico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual a condição (Ex: Autismo)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da mensalidade padrão'),
        ),
    ]
