# Generated by Django 5.2.8 on 2026-01-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_alter_aluno_tipo_atipico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, help_text='Digite DDD + Número (Ex: 11999998888)', max_length=20, null=True, verbose_name='WhatsApp do Responsável'),
        ),
    ]
