# Generated by Django 5.2.8 on 2026-01-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0017_aluno_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='tipo_atipico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
