# Generated by Django 5.2.8 on 2026-01-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0018_alter_aluno_tipo_atipico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=5, help_text='Dia fixo para vencimento (Ex: 5, 10, 15)', verbose_name='Dia de Vencimento'),
        ),
    ]
