# Generated by Django 5.2.8 on 2026-01-19 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0019_aluno_dia_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=5, help_text='Dia fixo para vencimento (Ex: 5, 10, 15)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento'),
        ),
    ]
