# Generated by Django 5.2.10 on 2026-05-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0021_alter_aluno_valor_mensalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dia_aula',
            field=models.CharField(blank=True, help_text='Ex: Segunda e Quarta', max_length=100, null=True, verbose_name='Dias de Aula'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='horario_aula',
            field=models.CharField(blank=True, help_text='Ex: 15:00 às 16:00', max_length=50, null=True, verbose_name='Horário'),
        ),
    ]
